/**
 * lib/supabase/mock-data.ts
 *
 * Typed mock data derived from the HTML mockup (construirfacil-catalog.html).
 * Used when NEXT_PUBLIC_SUPABASE_URL is not set — allows full UI development
 * without a live Supabase instance.
 */

import type { HouseModelWithConstructora, HouseModelDetail } from '@/types/database'

// ---------------------------------------------------------------------------
// Shared mock entities
// ---------------------------------------------------------------------------

const CONSTRUCTORA_MADERAS = {
  id: 'cst-maderas',
  name: 'Maderas del Sur',
  slug: 'maderas-del-sur',
  logo_url: null,
  city: 'Rosario',
  province: 'Santa Fe',
}

const CONSTRUCTORA_STEELWORKS = {
  id: 'cst-steelworks',
  name: 'SteelWorks AR',
  slug: 'steelworks-ar',
  logo_url: null,
  city: 'Buenos Aires',
  province: 'Buenos Aires',
}

const CONSTRUCTORA_BIOCASA = {
  id: 'cst-biocasa',
  name: 'BioCasa',
  slug: 'biocasa',
  logo_url: null,
  city: 'Córdoba',
  province: 'Córdoba',
}

const SYSTEM_WOOD: HouseModelWithConstructora['construction_system'] = {
  id: 'sys-wood',
  name: 'Wood Framing Plus',
  slug: 'wood-frame',
}

const SYSTEM_STEEL: HouseModelWithConstructora['construction_system'] = {
  id: 'sys-steel',
  name: 'Steel Frame',
  slug: 'steel-frame',
}

// ---------------------------------------------------------------------------
// Cover images scraped from posadasalrio.construirfacil.com
// ---------------------------------------------------------------------------

const _B = 'https://posadasalrio.construirfacil.com/wp-content/uploads/2025/11/'

const MOCK_COVER_IMAGES = [
  { storage_url: _B + 'R-2-PLANTAS-D3.1.jpg',                              alt_text: 'TIMBÓ II' },
  { storage_url: _B + 'Estilo-2-6.png',                                    alt_text: 'CEDRO I' },
  { storage_url: _B + 'casa3_opc1_2_posadas-2-1.jpg',                      alt_text: 'CEDRO II' },
  { storage_url: _B + 'R-2-PLANTAS-D1.2-1.jpg',                            alt_text: 'ROBLE III' },
  { storage_url: _B + '3opc2_PB_posadas.png',                              alt_text: 'ÁLAMO I' },
  { storage_url: _B + 'R-2-PLANTAS-D3.1.jpg',                              alt_text: 'PINO IV' },
  { storage_url: _B + 'casa3_opc1_2_posadas_PBjpg.jpg',                   alt_text: 'SAUCE I' },
  { storage_url: _B + 'living-t2.png',                                     alt_text: 'NOGAL II' },
  { storage_url: _B + 'R-2-PLANTAS-D-2.4.jpg',                             alt_text: 'EUCALIPTUS III' },
  { storage_url: _B + 'Image-from-Google-Drive-1-1-2.png',                 alt_text: 'JACARANDÁ I' },
  { storage_url: _B + 'Image-from-Google-Drive-2-2.png',                   alt_text: 'QUEBRACHO II' },
  { storage_url: _B + 'Interiores-Typologia-1-IMG2-2-e1764112587890.png',  alt_text: 'LAPACHO I' },
]

// ---------------------------------------------------------------------------
// Gradient classes — must match globals.css
// ---------------------------------------------------------------------------

export type GradientKey =
  | 'ph-timbo2' | 'ph-cedro1' | 'ph-cedro2' | 'ph-roble3'
  | 'ph-alamo1' | 'ph-pino4'  | 'ph-sauce1' | 'ph-nogal2'
  | 'ph-eucalip3' | 'ph-jacar1' | 'ph-quebr2' | 'ph-lapach1'

// ---------------------------------------------------------------------------
// Extended mock type — adds price tiers and gradient key
// ---------------------------------------------------------------------------

export interface MockHouseModel extends HouseModelWithConstructora {
  price_lista_usd: number
  price_contado_usd: number
  price_pozo_usd: number
  floors: number
  style: string
  tags: string[]
  gradient_key: GradientKey
  lqip_color: string
}

// ---------------------------------------------------------------------------
// The 12 seed houses
// ---------------------------------------------------------------------------

export const MOCK_HOUSES: MockHouseModel[] = [
  {
    id: 'hm-01',
    constructora_id: 'cst-maderas',
    name: 'TIMBÓ II',
    slug: 'timbo-ii',
    description: 'Casa de 2 plantas con diseño moderno, parrilla y lavadero. Ideal para familias que buscan amplitud y confort.',
    construction_system_id: 'sys-wood',
    bedrooms: 4,
    bathrooms: 3,
    total_area_m2: 298,
    covered_area_m2: 298,
    lot_area_m2: null,
    garage_spaces: 1,
    price_from_ars: null,
    price_from_usd: 349046,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-10T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
    constructora: CONSTRUCTORA_MADERAS,
    construction_system: SYSTEM_WOOD,
    cover_image: MOCK_COVER_IMAGES[0],
    price_lista_usd: 471213,
    price_contado_usd: 428375,
    price_pozo_usd: 349046,
    floors: 2,
    style: 'Moderno',
    tags: ['2 Plantas', 'Parrilla', 'Lavadero'],
    gradient_key: 'ph-timbo2',
    lqip_color: '#1c2d1a',
  },
  {
    id: 'hm-02',
    constructora_id: 'cst-maderas',
    name: 'CEDRO I',
    slug: 'cedro-i',
    description: 'Casa de planta baja compacta con deck exterior. Perfecta para lotes estrechos o como primera vivienda.',
    construction_system_id: 'sys-wood',
    bedrooms: 1,
    bathrooms: 1,
    total_area_m2: 127,
    covered_area_m2: 127,
    lot_area_m2: null,
    garage_spaces: null,
    price_from_ars: null,
    price_from_usd: 148755,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-12T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-11T00:00:00Z',
    updated_at: '2026-01-12T00:00:00Z',
    constructora: CONSTRUCTORA_MADERAS,
    construction_system: SYSTEM_WOOD,
    cover_image: MOCK_COVER_IMAGES[1],
    price_lista_usd: 201016,
    price_contado_usd: 180916,
    price_pozo_usd: 148755,
    floors: 1,
    style: 'Moderno',
    tags: ['1 Planta', 'Deck'],
    gradient_key: 'ph-cedro1',
    lqip_color: '#0d1f35',
  },
  {
    id: 'hm-03',
    constructora_id: 'cst-maderas',
    name: 'CEDRO II',
    slug: 'cedro-ii',
    description: 'Versión ampliada del Cedro con diseño versátil de 2 plantas. Admite entre 2 y 4 dormitorios según distribución.',
    construction_system_id: 'sys-wood',
    bedrooms: 3,
    bathrooms: 3,
    total_area_m2: 220,
    covered_area_m2: 220,
    lot_area_m2: null,
    garage_spaces: 1,
    price_from_ars: null,
    price_from_usd: 257685,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-15T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-13T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
    constructora: CONSTRUCTORA_MADERAS,
    construction_system: SYSTEM_WOOD,
    cover_image: MOCK_COVER_IMAGES[2],
    price_lista_usd: 348560,
    price_contado_usd: 316872,
    price_pozo_usd: 257685,
    floors: 2,
    style: 'Versátil',
    tags: ['2 Plantas', 'Versátil', 'Lavadero'],
    gradient_key: 'ph-cedro2',
    lqip_color: '#2a1f3d',
  },
  {
    id: 'hm-04',
    constructora_id: 'cst-steelworks',
    name: 'ROBLE III',
    slug: 'roble-iii',
    description: 'Diseño contemporáneo en 2 plantas. La estructura de Steel Frame permite grandes ventanales y espacios diáfanos.',
    construction_system_id: 'sys-steel',
    bedrooms: 3,
    bathrooms: 2,
    total_area_m2: 185,
    covered_area_m2: 185,
    lot_area_m2: null,
    garage_spaces: 1,
    price_from_ars: null,
    price_from_usd: 218000,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-18T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-16T00:00:00Z',
    updated_at: '2026-01-18T00:00:00Z',
    constructora: CONSTRUCTORA_STEELWORKS,
    construction_system: SYSTEM_STEEL,
    cover_image: MOCK_COVER_IMAGES[3],
    price_lista_usd: 293650,
    price_contado_usd: 265185,
    price_pozo_usd: 218000,
    floors: 2,
    style: 'Contemporáneo',
    tags: ['2 Plantas', 'Contemporáneo'],
    gradient_key: 'ph-roble3',
    lqip_color: '#3a1a0a',
  },
  {
    id: 'hm-05',
    constructora_id: 'cst-steelworks',
    name: 'ÁLAMO I',
    slug: 'alamo-i',
    description: 'Diseño minimalista de planta única. Eficiencia máxima en 96 m²: cocina integrada, dormitorio principal en suite.',
    construction_system_id: 'sys-steel',
    bedrooms: 2,
    bathrooms: 1,
    total_area_m2: 96,
    covered_area_m2: 96,
    lot_area_m2: null,
    garage_spaces: null,
    price_from_ars: null,
    price_from_usd: 112000,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-20T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-19T00:00:00Z',
    updated_at: '2026-01-20T00:00:00Z',
    constructora: CONSTRUCTORA_STEELWORKS,
    construction_system: SYSTEM_STEEL,
    cover_image: MOCK_COVER_IMAGES[4],
    price_lista_usd: 152064,
    price_contado_usd: 136352,
    price_pozo_usd: 112000,
    floors: 1,
    style: 'Minimalista',
    tags: ['1 Planta', 'Minimalista', 'Eficiente'],
    gradient_key: 'ph-alamo1',
    lqip_color: '#2a2620',
  },
  {
    id: 'hm-06',
    constructora_id: 'cst-maderas',
    name: 'PINO IV',
    slug: 'pino-iv',
    description: 'Casa premium de 2 plantas con piscina, terraza y SUM. El modelo más completo de la línea Maderas del Sur.',
    construction_system_id: 'sys-wood',
    bedrooms: 5,
    bathrooms: 4,
    total_area_m2: 340,
    covered_area_m2: 340,
    lot_area_m2: null,
    garage_spaces: 2,
    price_from_ars: null,
    price_from_usd: 399200,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-22T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-21T00:00:00Z',
    updated_at: '2026-01-22T00:00:00Z',
    constructora: CONSTRUCTORA_MADERAS,
    construction_system: SYSTEM_WOOD,
    cover_image: MOCK_COVER_IMAGES[5],
    price_lista_usd: 538950,
    price_contado_usd: 489300,
    price_pozo_usd: 399200,
    floors: 2,
    style: 'Premium',
    tags: ['2 Plantas', 'Piscina', 'Terraza', 'SUM'],
    gradient_key: 'ph-pino4',
    lqip_color: '#0c1f18',
  },
  {
    id: 'hm-07',
    constructora_id: 'cst-steelworks',
    name: 'SAUCE I',
    slug: 'sauce-i',
    description: 'La opción starter en Steel Frame. 78 m² bien resueltos para quienes priorizan la calidad constructiva sin exceso.',
    construction_system_id: 'sys-steel',
    bedrooms: 1,
    bathrooms: 1,
    total_area_m2: 78,
    covered_area_m2: 78,
    lot_area_m2: null,
    garage_spaces: null,
    price_from_ars: null,
    price_from_usd: 91260,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-25T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-23T00:00:00Z',
    updated_at: '2026-01-25T00:00:00Z',
    constructora: CONSTRUCTORA_STEELWORKS,
    construction_system: SYSTEM_STEEL,
    cover_image: MOCK_COVER_IMAGES[6],
    price_lista_usd: 123370,
    price_contado_usd: 111030,
    price_pozo_usd: 91260,
    floors: 1,
    style: 'Compacto',
    tags: ['1 Planta', 'Compacto', 'Starter'],
    gradient_key: 'ph-sauce1',
    lqip_color: '#0a1c28',
  },
  {
    id: 'hm-08',
    constructora_id: 'cst-maderas',
    name: 'NOGAL II',
    slug: 'nogal-ii',
    description: 'Planta baja con doble altura en living. Estética nórdica, terminaciones de madera vista y amplia luz natural.',
    construction_system_id: 'sys-wood',
    bedrooms: 2,
    bathrooms: 2,
    total_area_m2: 162,
    covered_area_m2: 162,
    lot_area_m2: null,
    garage_spaces: 1,
    price_from_ars: null,
    price_from_usd: 189900,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-01-28T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-27T00:00:00Z',
    updated_at: '2026-01-28T00:00:00Z',
    constructora: CONSTRUCTORA_MADERAS,
    construction_system: SYSTEM_WOOD,
    cover_image: MOCK_COVER_IMAGES[7],
    price_lista_usd: 256716,
    price_contado_usd: 231436,
    price_pozo_usd: 189900,
    floors: 1,
    style: 'Nórdico',
    tags: ['1 Planta', 'Nórdico', 'Doble altura'],
    gradient_key: 'ph-nogal2',
    lqip_color: '#281a08',
  },
  {
    id: 'hm-09',
    constructora_id: 'cst-steelworks',
    name: 'EUCALIPTUS III',
    slug: 'eucaliptus-iii',
    description: 'Diseño industrial de 2 plantas con mezzanine. Grandes aberturas metálicas y acabados en hormigón visto.',
    construction_system_id: 'sys-steel',
    bedrooms: 3,
    bathrooms: 3,
    total_area_m2: 265,
    covered_area_m2: 265,
    lot_area_m2: null,
    garage_spaces: 2,
    price_from_ars: null,
    price_from_usd: 310650,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-02-01T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-01-30T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
    constructora: CONSTRUCTORA_STEELWORKS,
    construction_system: SYSTEM_STEEL,
    cover_image: MOCK_COVER_IMAGES[8],
    price_lista_usd: 420050,
    price_contado_usd: 380200,
    price_pozo_usd: 310650,
    floors: 2,
    style: 'Industrial',
    tags: ['2 Plantas', 'Industrial', 'Mezzanine'],
    gradient_key: 'ph-eucalip3',
    lqip_color: '#1a1e1a',
  },
  {
    id: 'hm-10',
    constructora_id: 'cst-biocasa',
    name: 'JACARANDÁ I',
    slug: 'jacaranda-i',
    description: 'Casa de campo con galería perimetral y estética provenzal. Planta única luminosa con 2 dormitorios en suite.',
    construction_system_id: 'sys-wood',
    bedrooms: 2,
    bathrooms: 2,
    total_area_m2: 112,
    covered_area_m2: 112,
    lot_area_m2: null,
    garage_spaces: 1,
    price_from_ars: null,
    price_from_usd: 131040,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-02-05T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-02-03T00:00:00Z',
    updated_at: '2026-02-05T00:00:00Z',
    constructora: CONSTRUCTORA_BIOCASA,
    construction_system: SYSTEM_WOOD,
    cover_image: MOCK_COVER_IMAGES[9],
    price_lista_usd: 177408,
    price_contado_usd: 159360,
    price_pozo_usd: 131040,
    floors: 1,
    style: 'Provençal',
    tags: ['1 Planta', 'Provençal', 'Galería'],
    gradient_key: 'ph-jacar1',
    lqip_color: '#1e0c0c',
  },
  {
    id: 'hm-11',
    constructora_id: 'cst-steelworks',
    name: 'QUEBRACHO II',
    slug: 'quebracho-ii',
    description: 'El modelo más ambicioso del catálogo. 3 plantas, 5+ dormitorios, ascensor y SUM de 80 m² independiente.',
    construction_system_id: 'sys-steel',
    bedrooms: 5,
    bathrooms: 5,
    total_area_m2: 420,
    covered_area_m2: 420,
    lot_area_m2: null,
    garage_spaces: 2,
    price_from_ars: null,
    price_from_usd: 492960,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-02-08T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-02-06T00:00:00Z',
    updated_at: '2026-02-08T00:00:00Z',
    constructora: CONSTRUCTORA_STEELWORKS,
    construction_system: SYSTEM_STEEL,
    cover_image: MOCK_COVER_IMAGES[10],
    price_lista_usd: 665700,
    price_contado_usd: 602800,
    price_pozo_usd: 492960,
    floors: 3,
    style: 'Premium',
    tags: ['3 Plantas', 'Premium', 'Ascensor', 'SUM'],
    gradient_key: 'ph-quebr2',
    lqip_color: '#0e0e2a',
  },
  {
    id: 'hm-12',
    constructora_id: 'cst-biocasa',
    name: 'LAPACHO I',
    slug: 'lapacho-i',
    description: 'Diseño bioclimático con paneles solares integrados. Orientación norte optimizada y aislación térmica superior.',
    construction_system_id: 'sys-wood',
    bedrooms: 2,
    bathrooms: 2,
    total_area_m2: 145,
    covered_area_m2: 145,
    lot_area_m2: null,
    garage_spaces: 1,
    price_from_ars: null,
    price_from_usd: 169900,
    status: 'published',
    rejection_reason: null,
    published_at: '2026-02-10T00:00:00Z',
    reviewed_by: null,
    created_at: '2026-02-09T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
    constructora: CONSTRUCTORA_BIOCASA,
    construction_system: SYSTEM_WOOD,
    cover_image: MOCK_COVER_IMAGES[11],
    price_lista_usd: 229825,
    price_contado_usd: 207025,
    price_pozo_usd: 169900,
    floors: 1,
    style: 'Bioclimático',
    tags: ['1 Planta', 'Bioclimático', 'Paneles solares'],
    gradient_key: 'ph-lapach1',
    lqip_color: '#1a2010',
  },
]

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

export function getMockHouseBySlug(slug: string): MockHouseModel | undefined {
  return MOCK_HOUSES.find(h => h.slug === slug)
}

export function getMockHouseDetail(slug: string): (MockHouseModel & { attributes: { group: string; value: string }[] }) | undefined {
  const house = getMockHouseBySlug(slug)
  if (!house) return undefined

  const attributeMap: Record<string, { group: string; value: string }[]> = {
    'timbo-ii':       [{ group: 'Carpintería', value: 'DVH termopanel' }, { group: 'Techos', value: 'Chapa prepintada' }, { group: 'Pisos', value: 'Porcelanato 60×60' }, { group: 'Calefacción', value: 'Losa radiante' }],
    'cedro-i':        [{ group: 'Carpintería', value: 'Simple aluminio' }, { group: 'Techos', value: 'Chapa galvanizada' }, { group: 'Pisos', value: 'Cerámico 45×45' }, { group: 'Calefacción', value: 'Split inverter' }],
    'cedro-ii':       [{ group: 'Carpintería', value: 'DVH termopanel' }, { group: 'Techos', value: 'Chapa prepintada' }, { group: 'Pisos', value: 'Porcelanato 60×60' }, { group: 'Calefacción', value: 'Split inverter' }],
    'roble-iii':      [{ group: 'Carpintería', value: 'DVH termopanel' }, { group: 'Techos', value: 'Steel deck' }, { group: 'Pisos', value: 'Microhormigón' }, { group: 'Calefacción', value: 'Losa radiante' }],
    'alamo-i':        [{ group: 'Carpintería', value: 'Simple aluminio' }, { group: 'Techos', value: 'Steel deck' }, { group: 'Pisos', value: 'Porcelanato 60×60' }, { group: 'Calefacción', value: 'Split inverter' }],
    'pino-iv':        [{ group: 'Carpintería', value: 'Triple acristalado' }, { group: 'Techos', value: 'Verde extensivo' }, { group: 'Pisos', value: 'Madera maciza' }, { group: 'Calefacción', value: 'Losa radiante' }, { group: 'Extras', value: 'Piscina 8×4 m' }],
    'sauce-i':        [{ group: 'Carpintería', value: 'Simple aluminio' }, { group: 'Techos', value: 'Steel deck' }, { group: 'Pisos', value: 'Cerámico 45×45' }, { group: 'Calefacción', value: 'Split inverter' }],
    'nogal-ii':       [{ group: 'Carpintería', value: 'DVH termopanel' }, { group: 'Techos', value: 'Chapa prepintada' }, { group: 'Pisos', value: 'Madera maciza' }, { group: 'Calefacción', value: 'Losa radiante' }],
    'eucaliptus-iii': [{ group: 'Carpintería', value: 'Triple acristalado' }, { group: 'Techos', value: 'Steel deck' }, { group: 'Pisos', value: 'Microhormigón' }, { group: 'Calefacción', value: 'Losa radiante' }],
    'jacaranda-i':    [{ group: 'Carpintería', value: 'DVH termopanel' }, { group: 'Techos', value: 'Tejas francesas' }, { group: 'Pisos', value: 'Porcelanato 60×60' }, { group: 'Calefacción', value: 'Split inverter' }],
    'quebracho-ii':   [{ group: 'Carpintería', value: 'Triple acristalado' }, { group: 'Techos', value: 'Steel deck + Verde' }, { group: 'Pisos', value: 'Madera maciza' }, { group: 'Calefacción', value: 'Losa radiante' }, { group: 'Extras', value: 'Ascensor' }],
    'lapacho-i':      [{ group: 'Carpintería', value: 'DVH termopanel' }, { group: 'Techos', value: 'Verde extensivo' }, { group: 'Pisos', value: 'Porcelanato 60×60' }, { group: 'Calefacción', value: 'Losa radiante' }, { group: 'Energía', value: 'Paneles solares 6 kW' }],
  }

  return {
    ...house,
    attributes: attributeMap[slug] ?? [],
  }
}
